# Generated by Django 3.2 on 2021-04-27 17:01

import advito.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('about', models.TextField(blank=True, max_length=300, verbose_name='Информация о пользователе')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(upload_to=advito.models.user_avatar_path, verbose_name='Фото пользователя')),
                ('town', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('messages', models.ManyToManyField(blank=True, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Сообщения пользователю')),
                ('reviews', models.ManyToManyField(blank=True, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отзывы о пользователе')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('name_descript', models.CharField(blank=True, max_length=200, verbose_name='Название объявления')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание объявления')),
                ('image', models.ImageField(upload_to=advito.models.user_directory_path, verbose_name='Фото объявления')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата объявления')),
                ('date_adit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.categorypost', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.profile')),
                ('post', models.ManyToManyField(blank=True, related_name='post', to='advito.Post')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.post', verbose_name='Объявление')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=700)),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.post')),
            ],
        ),
    ]
