# Generated by Django 3.2 on 2021-04-29 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=300, verbose_name='Сообщение')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.profile', verbose_name='Автор сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('text', models.TextField(blank=True, max_length=300, verbose_name='Отзыв')),
                ('date_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.profile', verbose_name='Автор отзыва')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому отзыв')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='HistoryPost',
        ),
    ]
