# Generated by Django 3.2 on 2021-05-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0002_auto_20210429_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='to_whom',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_adit',
            new_name='date_edit',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='to_whom',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='advito.categorypost', verbose_name='Категория'),
        ),
    ]
