# Generated by Django 3.2 on 2021-06-09 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0003_auto_20210504_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AddField(
            model_name='message',
            name='in_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advito.post'),
        ),
    ]
